name: register_guest
dependencies:
  - python=3.6
  - pip:
      - django==3.0.3
      - djangorestframework==3.11.0
      - djangorestframework_simplejwt==4.4.0
      - django-cors-headers==3.2.1
      - markdown==3.2.1
      - gunicorn==20.0.4
      - coreapi==2.3.3
      - psycopg2-binary==2.8.4
      - flake8==3.7.9
